apply plugin: 'com.android.application'
apply from: '../.winboll/winboll_app_build.gradle'
apply from: '../.winboll/winboll_lint_build.gradle'

def genVersionName(def versionName){
    // 检查编译标志位配置
    assert (winbollBuildProps['stageCount'] != null)
    assert (winbollBuildProps['baseVersion'] != null)
    // 保存基础版本号
    winbollBuildProps.setProperty("baseVersion", "${versionName}");
    //保存编译标志配置
    FileOutputStream fos = new FileOutputStream(winbollBuildPropsFile)
    winbollBuildProps.store(fos, "${winbollBuildPropsDesc}");
    fos.close();
    
    // 返回编译版本号
    return "${versionName}." + winbollBuildProps['stageCount']
}

android {
	
	// 关键：改为你已安装的 SDK 32（≥ targetSdkVersion 30，兼容已安装环境）
    compileSdkVersion 32

    // 直接使用已安装的构建工具 33.0.3（无需修改）
    buildToolsVersion "33.0.3"
	
    defaultConfig {
        applicationId "cc.winboll.studio.positions"
        minSdkVersion 23
        targetSdkVersion 30
        versionCode 1
        // versionName 更新后需要手动设置 
        // .winboll/winbollBuildProps.properties 文件的 stageCount=0
        // Gradle编译环境下合起来的 versionName 就是 "${versionName}.0"
        versionName "15.12"
        if(true) {
            versionName = genVersionName("${versionName}")
        }
    }
	
	// 米盟 SDK
    packagingOptions {
         doNotStrip "*/*/libmimo_1011.so"
    }
}

dependencies {
	// 米盟
	api 'com.miui.zeus:mimo-ad-sdk:5.3.+'//请使用最新版sdk
     //注意：以下5个库必须要引入
    //api 'androidx.appcompat:appcompat:1.4.1'
    api 'androidx.recyclerview:recyclerview:1.0.0'
    api 'com.google.code.gson:gson:2.8.5'
    api 'com.github.bumptech.glide:glide:4.9.0'
    //annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'
	
	// https://mvnrepository.com/artifact/com.jzxiang.pickerview/TimePickerDialog
	api 'com.jzxiang.pickerview:TimePickerDialog:1.0.1'
	
	// 谷歌定位服务核心依赖（FusedLocationProviderClient所在库）
    api 'com.google.android.gms:play-services-location:21.0.1'
    
    // SSH
    api 'com.jcraft:jsch:0.1.55'
    // Html 解析
    api 'org.jsoup:jsoup:1.13.1'
    // 二维码类库
    api 'com.google.zxing:core:3.4.1'
    api 'com.journeyapps:zxing-android-embedded:3.6.0'
    // 应用介绍页类库
    api 'io.github.medyo:android-about-page:2.0.0'
    // 网络连接类库
    api 'com.squareup.okhttp3:okhttp:4.4.1'
    // AndroidX 类库
    api 'androidx.appcompat:appcompat:1.1.0'
    api 'com.google.android.material:material:1.4.0'
    //api 'androidx.viewpager:viewpager:1.0.0'
    //api 'androidx.vectordrawable:vectordrawable:1.1.0'
    //api 'androidx.vectordrawable:vectordrawable-animated:1.1.0'
    //api 'androidx.fragment:fragment:1.1.0'
    
	// WinBoLL库 nexus.winboll.cc 地址
	api 'cc.winboll.studio:libaes:15.15.9'
    api 'cc.winboll.studio:libappbase:15.15.21'
	
	// WinBoLL备用库 jitpack.io 地址
	//api 'com.github.ZhanGSKen:AES:aes-v15.12.9'
	//api 'com.github.ZhanGSKen:APPBase:appbase-v15.14.1'
	
	api fileTree(dir: 'libs', include: ['*.jar'])
}
