apply plugin: 'com.android.library'
apply plugin: 'maven-publish'
apply from: '../.winboll/winboll_lib_build.gradle'
apply from: '../.winboll/winboll_lint_build.gradle'

android {
	// 适配MIUI12
	compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 30
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
     compileOptions {
         sourceCompatibility JavaVersion.VERSION_1_7
         targetCompatibility JavaVersion.VERSION_1_7
     }
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])

    // JSch for SFTP
    api 'com.jcraft:jsch:0.1.55'
    // Gson for JSON
    api 'com.google.code.gson:gson:2.8.9'
    // OkHttp for HTTP
    api 'com.squareup.okhttp3:okhttp:3.12.13'
}
