// WinBoLL 应用签名配置
//

android {
	def winbollProps = new Properties()
    def winbollPropsFile = rootProject.file("${winbollFilePath}")
    if(winbollPropsFile.exists()) {
        winbollProps.load(new FileInputStream(winbollPropsFile))
	}
    
    // 读取秘钥配置文件
    //
    def keyProps = new Properties()
    def keyPropsFile = rootProject.file("${keyPropsFilePath}")
    //println 'Test keystore path'
    //println 'KeyProsFile :' + Boolean.toString(keyPropsFile.exists())
    //assert(false)
    if(keyPropsFile.exists()) {
		keyProps.load(new FileInputStream(keyPropsFile))
	}
    
    // 配置签名
    signingConfigs {
		if(keyPropsFile.exists()) {
            winboll {
                assert(keyProps['keyAlias'] != null && keyProps['keyPassword'] != null && keyProps['storeFile'] != null && keyProps['storePassword'] != null)
                keyAlias keyProps['keyAlias']
                keyPassword keyProps['keyPassword']
                storeFile keyProps['storeFile'] ? file(keyProps['storeFile']) : null
                storePassword keyProps['storePassword']
            }
		}
    }
    buildTypes {
        debug {
			if(keyPropsFile.exists()) {
			    signingConfig signingConfigs.winboll
		    }
         }
        release {
			if(keyPropsFile.exists()) {
			    signingConfig signingConfigs.winboll
			}
			
            minifyEnabled true // 开启混淆（核心开关）
            shrinkResources true // 可选：移除无用资源（进一步减小体积）
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), // 官方默认规则（优化版）
                          'proguard-rules.pro' // 自定义规则文件
         }
		 
    }
    
    flavorDimensions "WinBoLLApp"
    productFlavors {
        beta {
            // 检查编译标志位配置
            assert (winbollBuildProps['buildCount'] != null)
            dimension "WinBoLLApp"
            applicationIdSuffix ".beta"
            LocalDateTime localDateTimeNow = LocalDateTime.now(ZoneId.of("Asia/Shanghai"));
            versionNameSuffix "-beta" + winbollBuildProps['buildCount'] + "_" + localDateTimeNow.format('mmss')
        }
        stage {
            dimension "WinBoLLApp"
        }
    }
	
	compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

    // 应用包输出配置
    //
    android.applicationVariants.all { variant ->
        //
        // GitHub 应用包输出配置
        // 1. 配置 Beta Release 版应用包输出
        // 注意 ：GitHub 打包使用 android.yml 的 "bash ./gradlew assembleBetaRelease" 命令
        //
        if(variant.flavorName == "beta" && variant.buildType.name == "release") {
            /* 后期管理预留代码 */
            /* 暂时没有需要的 GitHub 应用包输出配置 */
            /* GitHub 部分代码忽略 */
        }
        
        //
        // WinBoLL 应用包输出配置
        // 1. 配置 Stage Release 版应用包输出
        // 2. 配置 Beta Debug 版应用包输出
	    //
        if((variant.flavorName == "beta" && variant.buildType.name == "debug")
        || (variant.flavorName == "beta" && variant.buildType.name == "release")
        || (variant.flavorName == "stage" && variant.buildType.name == "debug")
        || (variant.flavorName == "stage" && variant.buildType.name == "release")) {
            println "Project root directory: " + project.rootDir.toString()
            println "Project root directory name : " + project.rootDir.name
            def outputPath="${project.projectDir.absolutePath}/build/outputs/apk/${variant.buildType.name}"
            //def outputFileName="${rootProject.name}_${versionName}.apk"
            def outputFileName=project.rootDir.name + "_${versionName}.apk"
            
            // 创建 WinBoLL Studio 发布接口文件夹
            File fWinBoLLStudioDir = file("/sdcard/WinBoLLStudio/APKs");
			// 如果配置了APK接口文件夹路径，就设置应用APK输出文件夹为接口文件夹。
			if(winbollProps != null && winbollProps['APKOutputPath'] != null ) {
                fWinBoLLStudioDir = file(winbollProps['APKOutputPath']);
			}
			
            if(!fWinBoLLStudioDir.exists()) {
                println "[ WinBoLLStudio ] : " + fWinBoLLStudioDir.getAbsolutePath() + " Folder does not exist."
                println '[ WinBoLLStudio ] : The APKOutputPath property is not defined in winboll.properties, please configure APK output folder first.'
			} else {
                /// WINBOLL 主机的 APK 发布和源码管理操作 ///
                variant.getAssembleProvider().get().doFirst {
                    /* 后期管理预留代码 */
                } //doFirst {
                
                // 编译输出后处理文件部分
                //
                variant.getAssembleProvider().get().doLast {
                        variant.outputs.forEach{ file->
                            // 如果正在调试，就拷贝到 WinBoLL 备份管理文件夹
                            // 
                            if(variant.flavorName == "beta"&&variant.buildType.name == "debug"){
                                File outBuildBckDir = new File(fWinBoLLStudioDir, "/" + project.rootDir.name + "/${variant.buildType.name}")
                                // 创建目标路径目录
                                if(!outBuildBckDir.exists()) {
                                    outBuildBckDir.mkdirs();
                                    println "Output Folder Created.(WinBoLLStudio) : " + outBuildBckDir.getAbsolutePath()
                                }
                                if(outBuildBckDir.exists()) {
                                    def targetApkFile = new File(outBuildBckDir, outputFileName)
                                    copy{
                                        from file.outputFile
                                        into outBuildBckDir
                                        rename {
                                            String fileName -> "${outputFileName}"
                                        }
                                        println "Output APK (WinBoLLStudio): " + outBuildBckDir.getAbsolutePath() + "/${outputFileName}"
                                    }
                                    // ========== 设置文件权限为775 ==========
                                    if(targetApkFile.exists()){
                                        exec {
                                            commandLine 'chmod', '775', targetApkFile.absolutePath
                                        }
                                        println "Set file permission to 775 : ${targetApkFile.absolutePath}"
                                    }

                                    // 检查编译标志位配置
                                    assert (winbollBuildProps['buildCount'] != null)
                                    assert (winbollBuildProps['libraryProject'] != null)
                                    //构建计数增加
                                    int buildCount = Integer.parseInt(winbollBuildProps['buildCount']) + 1;
                                    // 设置编译计数
                                    winbollBuildProps.setProperty("buildCount", Integer.toString(buildCount));
                                    
                                    //保存编译标志配置
                                    FileOutputStream fos = new FileOutputStream(winbollBuildPropsFile)
                                    winbollBuildProps.store(fos, "${winbollBuildPropsDesc}");
                                    fos.close();
									println "\n\n>>> Project build.properties saved.\n\n";
                                    
                                    if(winbollBuildProps['libraryProject'] != "") {
                                        // 如果应用 build.properties 文件设置了类库模块项目文件名
                                        // 就拷贝一份新的编译标志配置到类库项目文件夹
                                        File libraryProjectBuildPropsFile = new File("$RootProjectDir/" + winbollBuildProps['libraryProject'] + "/build.properties")
                                        assert(winbollBuildPropsFile.exists())
                                        assert(libraryProjectBuildPropsFile.exists())
                                        java.nio.file.Path sourceFilePath = winbollBuildPropsFile.toPath();
                                        java.nio.file.Path targetFilePath = libraryProjectBuildPropsFile.toPath();
                                        java.nio.file.Files.copy(sourceFilePath, targetFilePath, java.nio.file.StandardCopyOption.REPLACE_EXISTING);
										
										println "\n\n>>> Library Project build.properties saved.\n\n";
                                    }
                                }
                            }
                            
                            // 如果正在发布，就拷贝到 WinBoLL 标签管理文件夹，和处理 Git 仓库管理任务。
                            //
                            if(variant.flavorName == "stage"&&variant.buildType.name == "release"){
                                // 发布 APK 文件
                                String szVersionName = "${versionName}"
                                String[] szlistTemp = szVersionName.split("-")
                                String szShortVersionName = szlistTemp[0]
                                String szCommonTagAPKName = project.rootDir.name + "_" + szShortVersionName + ".apk"
                                println "CommonTagAPKName is : " + szCommonTagAPKName
                                
                                File outTagDir = new File(fWinBoLLStudioDir, "/" + project.rootDir.name + "/tag/")
                                // 创建目标路径目录
                                if(!outTagDir.exists()) {
                                    outTagDir.mkdirs();
                                    println "Output Folder Created.(Tags) : " + outTagDir.getAbsolutePath()
                                }
                                
                                if(outTagDir.exists()) {
                                    File targetAPK = new File(outTagDir, "${szCommonTagAPKName}")
                                    if(targetAPK.exists()) {
                                        assert (!targetAPK.exists())
                                    }
                                    // 复制完整版APK
                                    def fullApkFile = new File(outTagDir, outputFileName)
                                    copy{
                                        from file.outputFile
                                        into outTagDir
                                        rename {
                                            String fileName -> "${outputFileName}"
                                        }
                                        println "Output APK (Tags): "+ outTagDir.getAbsolutePath() + "/${outputFileName}"
                                    }
                                    // 设置权限775。
                                    if(fullApkFile.exists()){
                                        exec {
                                            commandLine 'chmod', '775', fullApkFile.absolutePath
                                        }
                                        println "Set file permission to 775 : ${fullApkFile.absolutePath}"
                                    }

                                    // 复制短版本名APK
                                    def shortApkFile = new File(outTagDir, szCommonTagAPKName)
                                    copy{
                                        from file.outputFile
                                        into outTagDir
                                        rename {
                                            String fileName -> "${szCommonTagAPKName}"
                                        }
                                        println "Output APK (Tags): "+ outTagDir.getAbsolutePath() + "/${szCommonTagAPKName}"
                                    }
                                    // 设置权限775。
                                    if(shortApkFile.exists()){
                                        exec {
                                            commandLine 'chmod', '775', shortApkFile.absolutePath
                                        }
                                        println "Set file permission to 775 : ${shortApkFile.absolutePath}"
                                    }

                                    // 检查编译标志位配置
                                    assert (winbollBuildProps['stageCount'] != null)
                                    assert (winbollBuildProps['publishVersion'] != null)
                                    assert (winbollBuildProps['buildCount'] != null)
                                    assert (winbollBuildProps['baseVersion'] != null)
                                    assert (winbollBuildProps['baseBetaVersion'] != null)
                                    assert (winbollBuildProps['libraryProject'] != null)
                                    
                                    // 设置类库的默认版本名
                                    winbollBuildProps.setProperty("publishVersion", "${versionName}");
                                    // Stage 发布计数增加
                                    int stageCount = Integer.parseInt(winbollBuildProps['stageCount']) + 1;
                                    winbollBuildProps.setProperty("stageCount", Integer.toString(stageCount));
                                    // 设置类库的默认Beta版本名
                                    winbollBuildProps.setProperty("baseBetaVersion", winbollBuildProps['baseVersion'] + "." + Integer.toString(stageCount));
                                    // 构建计数重置
                                    winbollBuildProps.setProperty("buildCount", "0");
                                    
                                    //保存编译标志配置
                                    FileOutputStream fos = new FileOutputStream(winbollBuildPropsFile)
                                    winbollBuildProps.store(fos, "${winbollBuildPropsDesc}");
                                    fos.close();
                                    
                                    if(winbollBuildProps['libraryProject'] != "") {
                                        File libraryProjectBuildPropsFile = new File("$RootProjectDir/" + winbollBuildProps['libraryProject'] + "/build.properties")
                                        assert(winbollBuildPropsFile.exists())
                                        assert(libraryProjectBuildPropsFile.exists())
                                        java.nio.file.Path sourceFilePath = winbollBuildPropsFile.toPath();
                                        java.nio.file.Path targetFilePath = libraryProjectBuildPropsFile.toPath();
                                        java.nio.file.Files.copy(sourceFilePath, targetFilePath, java.nio.file.StandardCopyOption.REPLACE_EXISTING);
                                    }
                                    
                                    // 提交新的编译标志配置
									println 'exec bashCommitAppPublishBuildFlagInfoFilePath ...'
                                    def resultCommitBuildFlag = exec {
                                        commandLine 'bash', '--', "${RootProjectDir}/${bashCommitAppPublishBuildFlagInfoFilePath}", "${RootProjectDir}", "${versionName}", variant.buildType.name , rootProject.name
                                    }
                                    // 检查bash命令的返回值（假设非零表示失败）
                                    assert(resultCommitBuildFlag.getExitValue() == 0)
                                }
                            } //  if(variant.buildType.name == "release"){
							
							// 如果正在调试发布版，就只生成和输出APK文件，不处理 Git 仓库提交与更新问题。
							//
					        if(variant.flavorName == "stage"&&variant.buildType.name == "debug"){
                                String szVersionName = "${versionName}"
                                String[] szlistTemp = szVersionName.split("-")
                                String szShortVersionName = szlistTemp[0]
                                String szCommonTagAPKName = project.rootDir.name + "_" + szShortVersionName + ".apk"
                                println "CommonTagAPKName is : " + szCommonTagAPKName
                                
                                File outTagDir = new File(fWinBoLLStudioDir, "/" + project.rootDir.name + "/${variant.buildType.name}/")
                                // 创建目标路径目录
                                if(!outTagDir.exists()) {
                                    outTagDir.mkdirs();
                                    println "Output Folder Created.(Tags) : " + outTagDir.getAbsolutePath()
                                }
                                
                                if(outTagDir.exists()) {
                                    File targetAPK = new File(outTagDir, "${szCommonTagAPKName}")
                                    if(targetAPK.exists()) {
										println '如果是在调试 Stage 版应用包构建，请删除(注：在debug目录)现有的 Stage 应用包('+targetAPK.getAbsolutePath()+')。再编译一次。'
                                        assert (!targetAPK.exists())
                                    }
                                    // 复制完整版APK
                                    def debugFullApk = new File(outTagDir, outputFileName)
                                    copy{
                                        from file.outputFile
                                        into outTagDir
                                        rename {
                                            String fileName -> "${outputFileName}"
                                        }
                                        println "Output APK (Tags): "+ outTagDir.getAbsolutePath() + "/${outputFileName}"
                                    }
                                    // 权限设为775。
                                    if(debugFullApk.exists()){
                                        exec {
                                            commandLine 'chmod', '775', debugFullApk.absolutePath
                                        }
                                        println "Set file permission to 775 : ${debugFullApk.absolutePath}"
                                    }

                                    // 复制短版本名APK
                                    def debugShortApk = new File(outTagDir, szCommonTagAPKName)
                                    copy{
                                        from file.outputFile
                                        into outTagDir
                                        rename {
                                            String fileName -> "${szCommonTagAPKName}"
                                        }
                                        println "Output APK (Tags): "+ outTagDir.getAbsolutePath() + "/${szCommonTagAPKName}"
                                    }
                                    // 权限设为775
                                    if(debugShortApk.exists()){
                                        exec {
                                            commandLine 'chmod', '775', debugShortApk.absolutePath
                                        }
                                        println "Set file permission to 775 : ${debugShortApk.absolutePath}"
                                    }
                                }
                            }
                            
                            // 如果配置了APK额外输出路径，就复制一份拷贝到额外路径。
                            //
							if(winbollProps != null && winbollProps['ExtraAPKOutputPath'] != null ) {
                                File apkFile = new File(winbollProps['ExtraAPKOutputPath'])
								File outCommonDir = apkFile.getParentFile();
                                String commandAPKName = apkFile.getName();
                                if(outCommonDir.exists()) {
                                    copy{
                                        from file.outputFile
                                        into outCommonDir
                                        rename {
                                            String fileName -> "${commandAPKName}"
                                        }
                                        println "Output APK (Common): " + outCommonDir.getAbsolutePath() + "/${commandAPKName}"
                                    }
                                    // 额外输出文件设置775权限
                                    if(apkFile.exists()){
                                        exec {
                                            commandLine 'chmod', '775', apkFile.absolutePath
                                        }
                                        println "Set file permission to 775 : ${apkFile.absolutePath}"
                                    }
                                }
						    }
                            
                        
                    }
	            }// End of (variant.getAssembleProvider().get().doLast {)
            }/// WINBOLL 主机的 APK 发布和源码管理操作结束 ///
        }
        
    } // End of (android.applicationVariants.all { variant ->)
}

