apply plugin: 'com.android.library'
apply plugin: 'maven-publish'
apply from: '../.winboll/winboll_lib_build.gradle'
apply from: '../.winboll/winboll_lint_build.gradle'

android {
	// 适配MIUI12
	compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 30
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
	// 网络连接类库
    api 'com.squareup.okhttp3:okhttp:4.4.1'
	// Gson
	api 'com.google.code.gson:gson:2.8.9'
    // Html 解析
    api 'org.jsoup:jsoup:1.13.1'
	// 添加JSch依赖（SFTP核心，com.jcraft:jsch:0.1.54）
	api 'com.jcraft:jsch:0.1.54'
	
	// 米盟
	api 'com.miui.zeus:mimo-ad-sdk:5.3.+'//请使用最新版sdk
     //注意：以下5个库必须要引入
    //implementation 'androidx.appcompat:appcompat:1.4.1'
    api 'androidx.recyclerview:recyclerview:1.0.0'
    api 'com.google.code.gson:gson:2.8.5'
    api 'com.github.bumptech.glide:glide:4.9.0'
    //annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'
	
	// WinBoLL库 nexus.winboll.cc 地址
    //api 'cc.winboll.studio:libappbase:15.20.22'
    //api 'cc.winboll.studio:libaes:15.20.12'
	
	// 备用库 jitpack.io 地址
	api 'com.github.ZhanGSKen:libappbase:appbase-v15.20.22'
	api 'com.github.ZhanGSKen:libaes:aes-v15.20.12'
	
    api fileTree(dir: 'libs', include: ['*.jar'])
}
